name: server
description: Oh Hell multiplayer game server.
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.0
  ohhell_engine:
    path: ../packages/ohhell_engine
  ohhell_protocol:
    path: ../packages/ohhell_protocol

dev_dependencies:
  http: ^1.2.2
  lints: ^5.0.0
  test: ^1.25.6
